### ISSUE TITLE
64-bit compatibility

### ISSUE THREAD

**Issue by adl1995** [sbmelvin/SPC-PLAYER#3]
I tried compiling your software on Ubuntu 14.04 (64-bit). The compiler spits out Assembler messages like the one's below:

`main.c: Assembler messages:
main.c:336: Error: `pusha' is not supported in 64-bit mode
main.c:336: Error: `popa' is not supported in 64-bit mode
main.c:340: Error: `pusha' is not supported in 64-bit mode
main.c:340: Error: `popa' is not supported in 64-bit mode
main.c:349: Error: `pusha' is not supported in 64-bit mode
main.c:349: Error: `popa' is not supported in 64-bit mode
main.c:355: Error: `pusha' is not supported in 64-bit mode
main.c:355: Error: `popa' is not supported in 64-bit mode
main.c:361: Error: `pusha' is not supported in 64-bit mode
main.c:361: Error: `popa' is not supported in 64-bit mode
main.c:366: Error: `pusha' is not supported in 64-bit mode
main.c:366: Error: `popa' is not supported in 64-bit mode
make: *** [main.o] Error 1`

**Comment by uyjulian** [comment]
Try replacing the asm files with newer c versions from newer versions of SNEeSe.
